packages:
  - packages/*
  - apps/*
  - "!apps/example"

catalog:
  commander: 14.0.0
  inquirer: 12.7.0
  chalk: 5.4.1
  cli-table3: 0.6.5
  ora: 8.2.0
  yaml: 2.8.0
  fs-extra: 11.3.0
  glob: 11.0.3
  semver: 7.7.2
  npm-registry-fetch: 18.0.2
  pacote: 21.0.0
  lodash: ^4.17.21
  rxjs: 7.8.2
  zod: 3.25.75
  typescript: 5.8.3
  tsup: ^8.3.5
  vitest: ^3.2.4
  eslint: 9.30.1
  "@eslint/js": ^9.30.1
  prettier: 3.6.2
  "@types/fs-extra": ^11.0.4
  "@types/lodash": ^4.17.20
  "@types/semver": ^7.7.0
  "@types/inquirer": ^9.0.8
  "@vitest/coverage-v8": ^3.2.4
  "@vitest/ui": ^3.2.4
  rimraf: ^6.0.1
  msw: ^2.10.3
  tsx: ^4.20.3
  turbo: ^2.5.6

catalogs:
  node18:
    "@types/node": 18.19.59
  node20:
    "@types/node": 20.17.14
  node22:
    "@types/node": 22.9.4
