# Example PNPM Workspace Configuration
# This demonstrates various catalog strategies and patterns

packages:
  - "packages/*"
  - "apps/*"

# Default catalog for most common dependencies
catalog:
  # Core frameworks
  react: ^18.2.0
  react-dom: ^18.2.0
  vue: ^3.4.0

  # TypeScript ecosystem
  typescript: ^5.3.0
  "@types/node": ^20.11.0
  "@types/react": ^18.2.0
  "@types/react-dom": ^18.2.0

  # Build tools
  vite: ^5.1.0
  webpack: ^5.90.0
  rollup: ^4.12.0

  # Testing
  vitest: ^1.3.0
  jest: ^29.7.0
  "@testing-library/react": ^14.2.0
  "@testing-library/jest-dom": ^6.4.0

  # Development tools
  eslint: ^8.56.0
  prettier: ^3.2.0

  # Utilities
  lodash: ^4.17.21
  axios: ^1.6.0
  chalk: ^5.3.0
  "@types/cors": ^2.8.17
  "@types/lodash": ^4.17.20

# Additional catalogs for different scenarios
catalogs:
  # Legacy React 17 support
  react17:
    react: ^17.0.2
    react-dom: ^17.0.2
    "@types/react": ^17.0.62
    "@types/react-dom": ^17.0.18
    "@testing-library/react": ^12.1.5

  # Latest/bleeding edge versions
  latest:
    react: ^18.2.0
    vue: ^3.4.0
    typescript: ^5.3.0
    vite: ^5.1.0
    vitest: ^1.3.0

  # Node.js specific versions
  node18:
    "@types/node": ^18.19.0

  node20:
    "@types/node": ^20.11.0

  # Development tools catalog
  devtools:
    eslint: ^8.56.0
    "@typescript-eslint/eslint-plugin": ^6.21.0
    "@typescript-eslint/parser": ^6.21.0
    prettier: ^3.2.0
    husky: ^9.0.0
    lint-staged: ^15.2.0

  # UI framework specific
  material-ui:
    "@mui/material": ^5.15.0
    "@mui/icons-material": ^5.15.0
    "@emotion/react": ^11.11.0
    "@emotion/styled": ^11.11.0

  # Server/API dependencies
  server:
    express: ^4.18.0
    fastify: ^4.26.0
    "@types/express": ^4.17.0
    cors: ^2.8.5
    helmet: ^7.1.0
