name: Release

on:
  push:
    branches: [main]
    paths:
      - ".changeset/**"
  workflow_dispatch:

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
      pull-requests: write
      id-token: write
      pages: write
      actions: write
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          registry-url: "https://registry.npmjs.org"

      - name: Build
        run: |
          # Build workspace packages first
          pnpm --filter @pcu/utils build
          pnpm --filter @pcu/core build
          # Then build all packages
          pnpm build

      - name: Create Release Pull Request or Publish CLI
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          commit: "chore: release CLI package"
          title: "chore: release CLI package"
          setupGitUser: true
          skipCI: true
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  deploy-docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Build Dependencies
        run: |
          # Build workspace dependencies first
          pnpm --filter @pcu/utils build
          pnpm --filter @pcu/core build

      - name: Configure Next.js for GitHub Pages
        run: |
          cd apps/docs
          # Create a temporary config for GitHub Pages deployment
          cat > next.config.temp.mjs << 'EOF'
          import nextMDX from '@next/mdx'
          import path from 'path'

          import { recmaPlugins } from './src/mdx/recma.mjs'
          import { rehypePlugins } from './src/mdx/rehype.mjs'
          import { remarkPlugins } from './src/mdx/remark.mjs'
          import withSearch from './src/mdx/search.mjs'

          const withMDX = nextMDX({
            options: {
              remarkPlugins,
              rehypePlugins,
              recmaPlugins,
            },
          })

          const isProd = process.env.NODE_ENV === 'production'

          /** @type {import('next').NextConfig} */
          const nextConfig = {
            output: 'export',
            trailingSlash: true,
            images: {
              unoptimized: true,
            },
            basePath: isProd ? '/pnpm-catalog-updates' : '',
            assetPrefix: isProd ? '/pnpm-catalog-updates/' : '',
            pageExtensions: ['js', 'jsx', 'ts', 'tsx', 'mdx'],
            outputFileTracingIncludes: {
              '/**/*': ['./src/app/**/*.mdx'],
            },
            webpack: (config) => {
              config.resolve.alias = {
                ...config.resolve.alias,
                '@': path.resolve('./src'),
              }
              return config
            },
          }

          export default withSearch(withMDX(nextConfig))
          EOF
          # Replace the config for build
          mv next.config.temp.mjs next.config.mjs

      - name: Build Documentation
        run: |
          cd apps/docs
          # Build documentation using pnpm
          NODE_ENV=production pnpm build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./apps/docs/out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
