name: Release

on:
  push:
    branches: [main]
    paths:
      - ".changeset/**"
      - "package.json"
      - "apps/cli/package.json"
      - "apps/docs/package.json"

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
      pull-requests: write
      id-token: write
      pages: write
      actions: write
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          registry-url: "https://registry.npmjs.org"

      - name: Build
        run: |
          # Build workspace packages first
          pnpm --filter @pcu/utils build
          pnpm --filter @pcu/core build
          # Then build all packages
          pnpm build

      - name: Generate automatic changeset
        run: |
          # Get latest commit messages since last release
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ -z "$LAST_TAG" ]; then
            COMMITS=$(git log --pretty=format:"- %s" --no-merges -n 10)
          else
            COMMITS=$(git log $LAST_TAG..HEAD --pretty=format:"- %s" --no-merges)
          fi

          # Create automatic changeset if none exists
          if [ -z "$(ls .changeset/*.md 2>/dev/null)" ]; then
            mkdir -p .changeset
            cat > .changeset/auto-release.md << EOF
          ---
          "pcu": patch
          ---

          Automated release

          $COMMITS
          EOF
          fi

      - name: Create Release Pull Request or Publish CLI
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          commit: "chore: release CLI package"
          title: "chore: release CLI package"
          setupGitUser: true
          skipCI: true
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        if: steps.changesets.outputs.published == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ fromJson(steps.changesets.outputs.publishedPackages)[0].version }}
          release_name: v${{ fromJson(steps.changesets.outputs.publishedPackages)[0].version }}
          body: |
            ## Changes

            ## Installation

            ```bash
            npm install -g pcu@${{ fromJson(steps.changesets.outputs.publishedPackages)[0].version }}
            ```

            ## Usage

            ### Quick Commands

            ```bash
            # Check for updates
            pcu -c

            # Update interactively
            pcu -i

            # Update with dry run
            pcu -u -d

            # Get workspace info
            pcu -s
            ```

            ### All Commands & Shortcuts

            | Command | Shorthand | Description |
            |---------|-----------|-------------|
            | `pcu check` | `pcu -c` | Check for outdated catalog dependencies |
            | `pcu update` | `pcu -u` | Update catalog dependencies |
            | `pcu analyze` | `pcu -a` | Analyze impact of dependency updates |
            | `pcu workspace` | `pcu -s` | Show workspace information and validation |
            | `pcu help` | `pcu -h` | Display help information |

            ### Common Examples

            ```bash
            # Interactive update with backup
            pcu -i -b

            # Update only minor versions
            pcu -u --target minor

            # Check specific catalog
            pcu -c --catalog node18

            # Analyze before updating
            pcu -a default react

            # Validate workspace
            pcu -s --validate
            ```

            For complete documentation, visit: https://github.com/houko/pnpm-catalog-updates#readme
          draft: false
          prerelease: false

  deploy-docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Build Dependencies
        run: |
          # Build workspace dependencies first
          pnpm --filter @pcu/utils build
          pnpm --filter @pcu/core build

      - name: Configure Next.js for GitHub Pages
        run: |
          cd apps/docs
          # Create a temporary config for GitHub Pages deployment
          cat > next.config.temp.mjs << 'EOF'
          import nextMDX from '@next/mdx'
          import path from 'path'

          import { recmaPlugins } from './src/mdx/recma.mjs'
          import { rehypePlugins } from './src/mdx/rehype.mjs'
          import { remarkPlugins } from './src/mdx/remark.mjs'
          import withSearch from './src/mdx/search.mjs'

          const withMDX = nextMDX({
            options: {
              remarkPlugins,
              rehypePlugins,
              recmaPlugins,
            },
          })

          const isProd = process.env.NODE_ENV === 'production'

          /** @type {import('next').NextConfig} */
          const nextConfig = {
            output: 'export',
            trailingSlash: true,
            images: {
              unoptimized: true,
            },
            basePath: isProd ? '/pnpm-catalog-updates' : '',
            assetPrefix: isProd ? '/pnpm-catalog-updates/' : '',
            pageExtensions: ['js', 'jsx', 'ts', 'tsx', 'mdx'],
            outputFileTracingIncludes: {
              '/**/*': ['./src/app/**/*.mdx'],
            },
            webpack: (config) => {
              config.resolve.alias = {
                ...config.resolve.alias,
                '@': path.resolve('./src'),
              }
              return config
            },
          }

          export default withSearch(withMDX(nextConfig))
          EOF
          # Replace the config for build
          mv next.config.temp.mjs next.config.mjs

      - name: Build Documentation
        run: |
          cd apps/docs
          # Build documentation using pnpm
          NODE_ENV=production pnpm build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./apps/docs/out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
